version: '3.9'
services:
  api:
    build: .
    volumes:
      - ./:/src/
    ports:
      - '3001:3001'
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGODB_USERNAME: ${MONGO_USERNAME}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
    command: ['npm', 'start']

  mongodb:
    image: mongo:latest
    ports: 
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: shortit
  mongo-express:
    image: mongo-express
    ports: 
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    restart: always
    depends_on: 
      - mongodb
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
